---
kind: pipeline
type: docker
name: deploy-to-server

steps:
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 129.28.44.109
    username:
      from_secret: SERVER_USERNAME
    password:
      from_secret: SERVER_PASSWORD
    script:
      - |
        set -e  # 遇到错误立即退出
        echo "=== 开始部署 ==="

        echo "1. 进入项目目录..."
        cd ~/image-viewer

        echo "2. 拉取最新代码..."
        git pull origin main

        echo "4. 重新构建并启动容器..."
        docker-compose up --build -d

        echo "5. 查看容器状态..."
        docker-compose ps

        echo "6. 查看最新日志..."
        docker-compose logs --tail=50

        echo "=== 部署完成 ==="

trigger:
  event:
    - push
  branch:
    - main
    - master