---
kind: pipeline
type: docker
name: deploy-to-server

steps:
- name: configure-docker-mirrors
  image: appleboy/drone-ssh
  settings:
    host: 129.28.44.109
    username:
      from_secret: SERVER_USERNAME
    password:
      from_secret: SERVER_PASSWORD
    script:
      - |
        set -e  # 遇到错误立即退出
        echo "=== 配置 Docker 镜像加速器 ==="
        
        # 创建 Docker 配置目录
        mkdir -p /etc/docker
        
        # 创建 daemon.json 配置文件，包含多个镜像加速器
        cat << EOF > /tmp/daemon.json
        {
          "registry-mirrors": [
            "https://docker.mirrors.ustc.edu.cn",
            "https://hub-mirror.c.163.com",
            "https://mirror.ccs.tencentyun.com",
            "https://registry.docker-cn.com"
          ],
          "insecure-registries": [],
          "debug": false
        }
        EOF
        
        # 将配置复制到正确位置（需要sudo权限）
        sudo cp /tmp/daemon.json /etc/docker/daemon.json
        
        # 重启 Docker 服务以应用配置
        sudo systemctl restart docker
        
        echo "Docker 镜像加速器配置完成"

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 129.28.44.109
    username:
      from_secret: SERVER_USERNAME
    password:
      from_secret: SERVER_PASSWORD
    script:
      - |
        set -e  # 遇到错误立即退出
        echo "=== 开始部署 ==="

        echo "1. 进入项目目录..."
        cd ~/image-viewer

        echo "2. 拉取最新代码..."
        git pull origin main

        echo "3. 重新构建并启动容器..."
        docker-compose up --build -d

        echo "4. 查看容器状态..."
        docker-compose ps

        echo "5. 查看最新日志..."
        docker-compose logs --tail=50

        echo "=== 部署完成 ==="

trigger:
  event:
    - push
  branch:
    - main
    - master