kind: pipeline
name: deploy-to-server

# 核心关键点
platform:
  os: linux
  arch: amd64

clone:
  disable: true  # 禁用自动克隆


steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 129.28.44.109
      username:
        from_secret: SERVER_USERNAME
      password:
        from_secret: SERVER_PASSWORD
      script:
        - |
          set -e  # 遇到错误立即退出
          echo "=== 开始部署 ==="

          echo "1. 进入项目目录..."
          cd ~/image-viewer

          echo "2. 拉取最新代码..."
          git pull origin main

          echo "3. 重新构建并启动容器..."
          docker-compose up --build -d

          echo "4. 查看容器状态..."
          docker-compose ps

          echo "5. 查看最新日志1..."
          docker-compose logs --tail=50

          echo "=== 部署完成 ==="

trigger:
  event:
    - push
    - promote

branches:
  include:
    - main
    - master