kind: pipeline
type: docker
name: search

steps:
  - name: prepare # 流水线名称
    image: node:14-alpine # 定义创建容器的Docker镜像
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: node-model
        path: /app/model # 将maven下载依赖的目录挂载出来，防止重复下载
      - name: node-cache
        path: /app/cache # 将maven下载依赖的目录挂载出来，防止重复下载
      - name: node-build
        path: /app/build # 将应用打包好的Jar和执行脚本挂载出来
    commands: # 定义在Docker容器中执行的shell命令
      - npm config set prefix "/app/model"
        npm config set cache "/app/cache"
      - npm config set registry https://registry.npm.taobao.org
      - npm config set sass_binary_site=https://npm.taobao.org/mirrors/node-sass
      - npm install
      - npm run build
      - cp -r dist /app/build/
      - cp Dockerfile /app/build/
      - cp default.conf /app/build/
      - cp run.sh /app/build/
  - name: build # 流水线名称
    image: plugins/docker
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: node-build
        path: /app/build # 将应用打包好的Jar和执行脚本挂载出来
      - name: docker
        path: /var/run/docker.sock # 挂载宿主机的docker
    settings:
      dockerfile: /app/build/Dockerfile
    commands: # 定义在Docker容器中执行的shell命令
      - cd /app/build
      - chmod +x run.sh
      - sh run.sh
      - docker ps
volumes: # 定义流水线挂载目录，用于共享数据
  - name: node-build
    host:
      path: /home/docker/drone/node/build # 从宿主机中挂载的目录
  - name: node-model
    host:
      path: /home/docker/drone/node/model
  - name: node-cache
    host:
      path: /home/docker/drone/node/cache
  - name: docker
    host:
      path: /var/run/docker.sock
